#!/bin/sh

SVR_URL="http://kin.is.kakaocorp.com"
CONF_REPO="es"
CONF_URL=${SVR_URL}/${CONF_REPO}

ES_DIR="elasticsearch"
LS_DIR="logstash"
KB_DIR="kibana"
FB_DIR="filebeat"
PKGS_DIR="packages"

USER=$(whoami)
PWD=$(pwd)

if [ $USER == "root" ]; then
	echo "root is not permitted"
	exit -1
fi


if [ $PWD != "/home/deploy/ELK" ]; then
	pwd
	echo "/home/deploy/ELK path is permitted only"
	exit -1
fi

function es_set 
{
	#${PKGS_DIR}/${ES_DIR}/bin/elasticsearch -d
	ES_CONF="es.yml"
	curl -s ${CONF_URL}/${ES_CONF} >> ${PKGS_DIR}/${ES_DIR}/config/elasticsearch.yml
}

function ls_set
{
	LS_CONF1="logstash.yml"
	LS_CONF2="pipelines.yml"
	LS_CONF3="logstash-sample.conf"
	wget ${CONF_URL}/${LS_CONF1} -O ${PKGS_DIR}/${LS_DIR}/config/${LS_CONF1}
	wget ${CONF_URL}/${LS_CONF2} -O ${PKGS_DIR}/${LS_DIR}/config/${LS_CONF2}
	wget ${CONF_URL}/${LS_CONF3} -O ${PKGS_DIR}/${LS_DIR}/config/${LS_CONF3}
}

function kb_set
{
	KB_CONF="kibana.yml"
	wget ${CONF_URL}/${KB_CONF} -O ${PKGS_DIR}/${KB_DIR}/config/${KB_CONF}
}

function fb_set
{
	FB_CONF="filebeat.yml"
	wget ${CONF_URL}/${FB_CONF} -O ${PKGS_DIR}/${FB_DIR}/${FB_CONF}
	#sudo chown root.root ${PKGS_DIR}/${FB_DIR}/${FB_CONF}
	#mkdir ${PKGS_DIR}/${FB_DIR}/data
	#mkdir ${PKGS_DIR}/${FB_DIR}/logs
}

if [ -z $1 ]; then
        echo "##################### Menu ##############"
        echo " $ ./elk [Command]"
        echo "#####################%%%%%%##############"
        echo "         es : elasticsearch start"
        echo "         ls : logstash config & start"
        echo "         kb : kibana config & start"
        echo "         fb : filebeat config & start"
        echo "#########################################";
        exit 1;
fi

case "$1" in
        "es" ) es_set;;
        "ls" ) ls_set ;;
        "kb" ) kb_set ;;
        "fb" ) fb_set ;;
        "all" ) es_set; ls_set; kb_set; fb_set ;;
        *) echo "Incorrect Command" ;;
esac
