#!/bin/sh

SVR_URL="http://kin.is.kakaocorp.com"
CONF_REPO="es"
CONF_URL=${SVR_URL}/${CONF_REPO}

ES_DIR="elasticsearch"
LS_DIR="logstash"
KB_DIR="kibana"
FB_DIR="filebeat"
PKGS_DIR="packages"

SYS_DIR="/etc/systemd/system"

USER=$(whoami)
PWD=$(pwd)

if [ $USER == "root" ]; then
	echo "root is not permitted"
	exit -1
fi


if [ $PWD != "/home/deploy/ELK" ]; then
	pwd
	echo "/home/deploy/ELK path is permitted only"
	exit -1
fi

function es_start
{
	${PKGS_DIR}/${ES_DIR}/bin/elasticsearch -d
}

function ls_start
{
	LS_SVC="logstash.service"
	sudo wget ${CONF_URL}/${LS_SVC} -O ${SYS_DIR}/${LS_SVC}
	daemon_reload
	sudo systemctl start ${LS_SVC} 
}

function kb_start
{
	KB_SVC="kibana.service"
	sudo wget ${CONF_URL}/${KB_SVC} -O ${SYS_DIR}/${KB_SVC}
	daemon_reload
	sudo systemctl start ${KB_SVC} 
}

function fb_start
{
	FB_SVC="filebeat.service"
	sudo wget ${CONF_URL}/${FB_SVC} -O ${SYS_DIR}/${FB_SVC}
	daemon_reload
	sudo systemctl start ${FB_SVC} 
}

function daemon_reload
{
	sudo systemctl daemon-reload
}

if [ -z $1 ]; then
        echo "##################### Menu ##############"
        echo " $ ./startelk [Command]"
        echo "#####################%%%%%%##############"
        echo "         es : elasticsearch start"
        echo "         ls : logstash start"
        echo "         kb : kibana start"
        echo "         fb : filebeat start"
        echo "         all : all start"
        echo "#########################################";
        exit 1;
fi

case "$1" in
        "es" ) es_start;;
        "ls" ) ls_start ;;
        "kb" ) kb_start ;;
        "fb" ) fb_start ;;
        "all" ) es_start; ls_start; kb_start; fb_start ;;
        *) echo "Incorrect Command" ;;
esac
