#!/bin/sh

SVR_URL="http://kin.is.kakaocorp.com"
CONF_REPO="es"
CONF_URL=${SVR_URL}/${CONF_REPO}

ES_DIR="elasticsearch"
LS_DIR="logstash"
KB_DIR="kibana"
FB_DIR="filebeat"
PKGS_DIR="packages"
SYS_DIR="/etc/systemd/system"

USER=$(whoami)
PWD=$(pwd)

if [ $USER == "root" ]; then
	echo "root is not permitted"
	exit -1
fi

if [ $PWD != "/home/deploy/ELK" ]; then
	pwd
	echo "/home/deploy/ELK path is permitted only"
	exit -1
fi

function es_set
{
	ES_CONF="elasticsearch.yml"

	wget ${CONF_URL}/${ES_CONF} -O ${PKGS_DIR}/${ES_DIR}/config/elasticsearch.yml
	${PKGS_DIR}/${ES_DIR}/bin/elasticsearch -d
}

function kb_set
{
	KB_CONF="kibana.yml"
	KB_SVC="kibana.service"

	wget ${CONF_URL}/${KB_CONF} -O ${PKGS_DIR}/${KB_DIR}/config/${KB_CONF}
	sudo wget ${CONF_URL}/${KB_SVC} -O ${SYS_DIR}/${KB_SVC}
	daemon_reload
	sudo systemctl start ${KB_SVC}
}

function fb_set
{
	FB_CONF="filebeat.yml"
	TG_CONF="filebeat.yml_tuto1"
	FB_SVC="filebeat.service"

	wget ${CONF_URL}/${TG_CONF} -O ${PKGS_DIR}/${FB_DIR}/${FB_CONF}
	sudo wget ${CONF_URL}/${FB_SVC} -O ${SYS_DIR}/${FB_SVC}
	daemon_reload
	sudo systemctl start ${FB_SVC}
}

function daemon_reload
{
	sudo systemctl daemon-reload
}

es_set; kb_set; fb_set
