#!/bin/sh

ES_URL="https://artifacts.elastic.co/downloads/elasticsearch"
LS_URL="https://artifacts.elastic.co/downloads/logstash"
KB_URL="https://artifacts.elastic.co/downloads/kibana"
FB_URL="https://artifacts.elastic.co/downloads/beats/filebeat"

VER="6.7.0"

ES="elasticsearch-${VER}.tar.gz"
LS="logstash-${VER}.tar.gz"
KB="kibana-${VER}-linux-x86_64.tar.gz"
FB="filebeat-${VER}-linux-x86_64.tar.gz"

ES_PKGS=${ES_URL}/${ES}
LS_PKGS=${LS_URL}/${LS}
KB_PKGS=${KB_URL}/${KB}
FB_PKGS=${FB_URL}/${FB}

ES_DIR="elasticsearch"
LS_DIR="logstash"
KB_DIR="kibana"
FB_DIR="filebeat"
PKGS_DIR="packages"
CONF_DIR="conf"
SYS_DIR="/etc/systemd/system"

ES_CONF="elasticsearch.yml"
KB_CONF="kibana.yml"
FB_CONF="filebeat.yml"
TG_CONF1="filebeat.yml_tuto1"
TG_CONF2="filebeat.yml_tuto2"

LS_CONF1="logstash.yml"
LS_CONF2="pipelines.yml"
LS_CONF3="logstash-sample.conf"

LS_SVC="logstash.service"
KB_SVC="kibana.service"
FB_SVC="filebeat.service"


USER=$(whoami)
PWD=$(pwd)

if [ $USER == "root" ]; then
	echo "root is not permitted"
	exit -1
fi

if [ $PWD != "/home/ec2-user/ES-Tutorial-ELK" ]; then
	pwd
	echo "/home/ec2-user/ES-Tutorial-ELK path is permitted only"
	exit -1
fi

function install_elk_packages
{

	sudo yum -y install wget
	mkdir ${PKGS_DIR}
	cd ${PKGS_DIR}

	wget ${ES_PKGS}
	wget ${LS_PKGS}
	wget ${KB_PKGS}
	wget ${FB_PKGS}

	tar xfz ${ES}
	tar xfz ${LS}
	tar xfz ${KB}
	tar xfz ${FB}

	ln -s ./elasticsearch-${VER} elasticsearch
	ln -s ./logstash-${VER} logstash
	ln -s ./kibana-${VER}-linux-x86_64 kibana
	ln -s ./filebeat-${VER}-linux-x86_64 filebeat

}

function es_set
{
	cp ${CONF_DIR}/${ES_CONF} -O ${PKGS_DIR}/${ES_DIR}/config/elasticsearch.yml
	${PKGS_DIR}/${ES_DIR}/bin/elasticsearch -d
}

function kb_set
{
	cp ${CONF_DIR}/${KB_CONF} -O ${PKGS_DIR}/${KB_DIR}/config/${KB_CONF}
	sudo cp ${CONF_DIR}/${KB_SVC} -O ${SYS_DIR}/${KB_SVC}
	daemon_reload
	sudo systemctl start ${KB_SVC}
}

function fb_set
{
	cp ${CONF_DIR}/${TG_CONF1} -O ${PKGS_DIR}/${FB_DIR}/${FB_CONF}
	sudo cp ${CONF_DIR}/${FB_SVC} -O ${SYS_DIR}/${FB_SVC}
	daemon_reload
	sudo systemctl start ${FB_SVC}
}

function es_start
{
        ${PKGS_DIR}/${ES_DIR}/bin/elasticsearch -d
}

function ls_start
{
        sudo cp ${CONF}/${LS_SVC} -O ${SYS_DIR}/${LS_SVC}
        daemon_reload
        sudo systemctl start ${LS_SVC}
}

function kb_start
{
        sudo cp ${CONF}/${KB_SVC} -O ${SYS_DIR}/${KB_SVC}
        daemon_reload
        sudo systemctl start ${KB_SVC}
}

function fb_start
{
        sudo cp ${CONF}/${FB_SVC} -O ${SYS_DIR}/${FB_SVC}
        daemon_reload
        sudo systemctl start ${FB_SVC}
}

function no_filter
{
        ${PKGS_DIR}/${LS_DIR}/bin/logstash -e 'input { stdin { } } output { stdout {} }'
}

function simple_filter
{
        ${PKGS_DIR}/${LS_DIR}/bin/logstash -f logstash_conf/simple.conf
}

function beats_filter
{
        cp ${CONF}/${TG_CONF2} -O ${PKGS_DIR}/${FB_DIR}/${FB_CONF}
        sudo systemctl restart ${FB_SVC}
        ${PKGS_DIR}/${LS_DIR}/bin/logstash -f logstash_conf/beats.conf
}

function apache_filter
{
        ${PKGS_DIR}/${LS_DIR}/bin/logstash -f logstash_conf/apache.conf
}

function last_filter
{
        ${PKGS_DIR}/${LS_DIR}/bin/logstash -f logstash_conf/es.conf
}

function systemd_filter
{
        cp ${CONF}/${LS_CONF1} -O ${PKGS_DIR}/${LS_DIR}/config/${LS_CONF1}
        cp ${CONF}/${LS_CONF2} -O ${PKGS_DIR}/${LS_DIR}/config/${LS_CONF2}
        cp ${CONF}/${LS_CONF3} -O ${PKGS_DIR}/${LS_DIR}/config/${LS_CONF3}
        sudo cp ${CONF}/${LS_SVC} -O ${SYS_DIR}/${LS_SVC}
        sudo systemctl daemon-reload
        sudo systemctl start ${LS_SVC}

}

function daemon_reload
{
	sudo systemctl daemon-reload
}


if [ -z $1 ]; then
        echo "##################### Menu ##############"
        echo " $ ./tuto [Command]"
        echo "#####################%%%%%%##############"
        echo "         1 : install elk packages"
        echo "         2 : set elk"
        echo "         3 : start elk"
        echo "         4 : standard input/output, no filters"
        echo "         5 : standard input/output, simple filter"
        echo "         6 : beats input, no filter, standard output"
        echo "         7 : beats input, grok filter COMBINEDAPACHELOG, standard output"
        echo "         8 : beats input, grok filter COMBINEDAPACHELOG, es output"
        echo "         9 : beats input, grok filter COMBINEDAPACHELOG, es output with systemd"
        echo "#########################################";
        exit 1;
fi

case "$1" in
        "1" ) install_elk_packages;;
        "2" ) es_set; kb_set; fb_set;;
        "3" ) es_start; ls_start; kb_start; fb_start;;
	"4" ) no_filter;;
        "5" ) simple_filter;;
        "6" ) beats_filter;;
        "7" ) apache_filter;;
        "8" ) last_filter;;
        "9" ) systemd_filter;;
        *) echo "Incorrect Command" ;;
esac
